import streamlit as st
import pandas as pd
from fpdf import FPDF
import os
from datetime import datetime
import gspread
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from streamlit_option_menu import option_menu
import requests

# --- 1. CONFIGURATION & ASSETS ---
COMPANY_NAME = "G P Group"
LOGO_PATH = "logo.png"

# --- 2. GOOGLE SERVICES (BACKEND) ---
SCOPES = ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]

def get_creds():
    return Credentials.from_service_account_info(st.secrets["gcp_service_account"], scopes=SCOPES)

def get_sheet_client():
    return gspread.authorize(get_creds())

def get_drive_service():
    return build('drive', 'v3', credentials=get_creds())

def upload_to_drive(file_path, filename, mime_type):
    """Uploads file to Google Drive (Shared Drive compatible)"""
    service = get_drive_service()
    folder_id = st.secrets["drive_settings"]["folder_id"]
    file_metadata = {'name': filename, 'parents': [folder_id]}
    media = MediaFileUpload(file_path, mimetype=mime_type)
    file = service.files().create(
        body=file_metadata, media_body=media, fields='id, webViewLink', supportsAllDrives=True
    ).execute()
    return file.get('webViewLink')

# --- 3. DATABASE OPERATIONS (CRUD) ---
def init_db():
    try:
        client = get_sheet_client()
        sh = client.open_by_url(st.secrets["drive_settings"]["sheet_url"])
        
        # Ensure tables exist with correct headers
        tables = {
            "DebitNotes": ["ID", "Contractor Name", "Date", "Amount", "Reason", "Site Location", "Image Links", "PDF Link", "SubmittedBy"],
            "Contractors": ["ID", "Name", "Details"],
            "Users": ["Username", "Password", "Role"]
        }
        for name, headers in tables.items():
            try: sh.worksheet(name)
            except: 
                ws = sh.add_worksheet(name, 100, len(headers))
                ws.append_row(headers)
    except Exception as e: st.error(f"Database Error: {e}")

def db_get(table):
    return pd.DataFrame(get_sheet_client().open_by_url(st.secrets["drive_settings"]["sheet_url"]).worksheet(table).get_all_records())

def db_insert(table, row_data):
    ws = get_sheet_client().open_by_url(st.secrets["drive_settings"]["sheet_url"]).worksheet(table)
    ws.append_row(row_data)

def db_delete(table, col_name, value):
    ws = get_sheet_client().open_by_url(st.secrets["drive_settings"]["sheet_url"]).worksheet(table)
    try:
        cell = ws.find(str(value))
        ws.delete_rows(cell.row)
        return True
    except: return False

def db_update_cell(table, search_val, col_idx, new_val):
    ws = get_sheet_client().open_by_url(st.secrets["drive_settings"]["sheet_url"]).worksheet(table)
    try:
        cell = ws.find(str(search_val))
        ws.update_cell(cell.row, col_idx, new_val)
        return True
    except: return False

# --- 4. PDF ENGINE ---
class PDF(FPDF):
    def header(self):
        if os.path.exists(LOGO_PATH): self.image(LOGO_PATH, 10, 8, 30)
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(50, 50, 50)
        self.cell(0, 15, COMPANY_NAME, 0, 1, 'C')
        self.ln(10)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150)
        self.cell(0, 10, f'Generated by {st.session_state.get("username", "System")} on {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')

def create_pdf(type, data):
    if not os.path.exists("temp"): os.makedirs("temp")
    pdf = PDF()
    pdf.add_page()
    
    # Header Styling
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_fill_color(240, 240, 240)
    title = "DEBIT NOTE" if type == "receipt" else "STATEMENT OF ACCOUNT"
    pdf.cell(0, 12, title, 0, 1, 'C', fill=True)
    pdf.ln(10)
    
    if type == "receipt":
        # Card-like details
        pdf.set_font("Helvetica", "", 12)
        fields = [
            ("Contractor", data['contractor']),
            ("Date", str(data['date'])),
            ("Site Location", data['site']),
            ("Amount", f"INR {data['amount']}")
        ]
        
        for label, value in fields:
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(50, 10, label, "B")
            pdf.set_font("Helvetica", "", 12)
            pdf.cell(140, 10, str(value), "B", 1)
            
        pdf.ln(10)
        pdf.set_font("Helvetica", "B", 12); pdf.cell(0, 10, "Description / Reason:", 0, 1)
        pdf.set_font("Helvetica", "", 11); pdf.multi_cell(0, 8, data['reason'])
        
        if data.get('local_img_paths'):
            pdf.ln(10)
            pdf.set_font("Helvetica", "B", 12); pdf.cell(0, 10, "Proof of Deduction:", 0, 1)
            for p in data['local_img_paths']:
                if os.path.exists(p): 
                    try: pdf.image(p, w=100); pdf.ln(5)
                    except: pass
        filename = f"DebitNote_{int(datetime.now().timestamp())}.pdf"

    else: # Statement
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 8, f"Contractor: {data['contractor']}", 0, 1)
        pdf.cell(0, 8, f"Period: {data['start']} to {data['end']}", 0, 1)
        pdf.ln(5)
        
        # Table Header
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_fill_color(50, 50, 50); pdf.set_text_color(255)
        pdf.cell(30, 10, "Date", 1, 0, 'C', True)
        pdf.cell(100, 10, "Reason", 1, 0, 'C', True)
        pdf.cell(30, 10, "Amount", 1, 0, 'C', True)
        pdf.cell(30, 10, "User", 1, 1, 'C', True)
        
        # Table Body
        pdf.set_text_color(0); pdf.set_font("Helvetica", "", 9)
        total = 0
        for _, row in data['df'].iterrows():
            pdf.cell(30, 10, str(row['Date']), 1)
            pdf.cell(100, 10, str(row['Reason'])[:55], 1)
            pdf.cell(30, 10, str(row['Amount']), 1)
            pdf.cell(30, 10, str(row['SubmittedBy']), 1, 1)
            total += float(row['Amount'])
            
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(130, 10, "Total Deductions:", 0, 0, 'R')
        pdf.cell(60, 10, f"INR {total}", 0, 1, 'L')
        filename = f"Statement_{data['contractor']}.pdf"

    path = f"temp/{filename}"
    pdf.output(path)
    return path

# --- 5. THEME ENGINE ---
THEMES = {
    "Corporate Blue": {
        "bg": "#f4f6f9", "card": "rgba(255, 255, 255, 0.9)", "text": "#1e293b", "primary": "#0F52BA", "accent": "#3b82f6"
    },
    "Dark Mode": {
        "bg": "#0f172a", "card": "rgba(30, 41, 59, 0.8)", "text": "#f8fafc", "primary": "#3b82f6", "accent": "#60a5fa"
    },
    "Industrial": {
        "bg": "#292524", "card": "rgba(68, 64, 60, 0.9)", "text": "#fafaf9", "primary": "#f59e0b", "accent": "#fbbf24"
    },
    "Forest": {
        "bg": "#ecfdf5", "card": "rgba(255, 255, 255, 0.8)", "text": "#064e3b", "primary": "#059669", "accent": "#34d399"
    },
    "High Contrast": {
        "bg": "#ffffff", "card": "#ffffff", "text": "#000000", "primary": "#000000", "accent": "#000000"
    }
}

def inject_css(theme_name):
    t = THEMES[theme_name]
    st.markdown(f"""
    <style>
        .stApp {{ background-color: {t['bg']}; color: {t['text']}; }}
        .glass-card {{
            background: {t['card']}; backdrop-filter: blur(10px);
            border-radius: 16px; padding: 24px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.1); margin-bottom: 24px;
        }}
        .stButton>button {{
            background: linear-gradient(135deg, {t['primary']} 0%, {t['accent']} 100%);
            color: white; border: none; padding: 10px 24px; border-radius: 8px; font-weight: 600; width: 100%;
        }}
        .stTextInput input, .stNumberInput input, .stDateInput input, .stSelectbox div[data-baseweb="select"] {{
            border-radius: 8px; border: 1px solid {t['primary']}40;
        }}
        h1, h2, h3 {{ color: {t['text']} !important; }}
    </style>
    """, unsafe_allow_html=True)

def card_start(): st.markdown('<div class="glass-card">', unsafe_allow_html=True)
def card_end(): st.markdown('</div>', unsafe_allow_html=True)

# --- 6. MAIN APP ---
def main():
    st.set_page_config(page_title="GP Group Portal", page_icon="🏗️", layout="wide")
    
    # Init Session
    if 'theme' not in st.session_state: st.session_state['theme'] = "Corporate Blue"
    if 'auth' not in st.session_state: st.session_state['auth'] = False
    
    inject_css(st.session_state['theme'])
    if 'db_init' not in st.session_state: init_db(); st.session_state['db_init'] = True

    # --- AUTH ---
    if not st.session_state['auth']:
        c1, c2, c3 = st.columns([1,1,1])
        with c2:
            card_start()
            st.title("G P Portal Login")
            u = st.text_input("Username")
            p = st.text_input("Password", type="password")
            if st.button("Login"):
                users = db_get("Users")
                match = users[(users['Username'].astype(str)==u) & (users['Password'].astype(str)==p)]
                if not match.empty:
                    st.session_state['auth'] = True
                    st.session_state['role'] = match.iloc[0]['Role']
                    st.session_state['username'] = u
                    st.rerun()
                else: st.error("Invalid Credentials")
            card_end()
        return

    # --- TOP BAR ---
    col_logo, col_space, col_user = st.columns([1, 4, 2])
    with col_logo:
        if os.path.exists(LOGO_PATH): st.image(LOGO_PATH, width=120)
    with col_user:
        with st.expander(f"👤 {st.session_state['username']} ({st.session_state['role']})"):
            if st.button("Logout"): st.session_state['auth'] = False; st.rerun()
            st.session_state['theme'] = st.selectbox("Theme", list(THEMES.keys()), index=list(THEMES.keys()).index(st.session_state['theme']))

    # --- SIDEBAR ---
    with st.sidebar:
        st.title("Navigation")
        opts = ["Dashboard", "Raise Debit Note"]
        icons = ["grid-fill", "file-earmark-plus-fill"]
        
        if st.session_state['role'] == "Admin":
            opts += ["Contractors", "User Management"]
            icons += ["building-fill", "people-fill"]
            
        sel = option_menu("Menu", opts, icons=icons, styles={"nav-link-selected": {"background-color": THEMES[st.session_state['theme']]['primary']}})

    # --- DASHBOARD ---
    if sel == "Dashboard":
        st.title("Dashboard")
        df = db_get("DebitNotes")
        
        # Search & Filter
        card_start()
        c1, c2, c3 = st.columns(3)
        search = c1.text_input("Search Contractor")
        
        # Sort & Filter Logic
        if not df.empty:
            df['Date'] = pd.to_datetime(df['Date'])
            min_d, max_d = df['Date'].min().date(), df['Date'].max().date()
            dr = c2.date_input("Date Range", [min_d, max_d])
            sort_order = c3.selectbox("Sort", ["Date (Desc)", "Date (Asc)"])
            
            # Apply Filters
            if search: df = df[df['Contractor Name'].str.contains(search, case=False)]
            if len(dr) == 2: df = df[(df['Date'].dt.date >= dr[0]) & (df['Date'].dt.date <= dr[1])]
            df = df.sort_values(by="Date", ascending=(sort_order == "Date (Asc)"))
        card_end()

        # Recent Activity
        st.subheader("Recent Activity")
        if not df.empty:
            st.dataframe(df.head(5)[['Date', 'Contractor Name', 'Amount', 'Reason', 'SubmittedBy']], use_container_width=True)
        else: st.info("No records found.")

        # Master PDF Button
        st.markdown("---")
        if st.button("📄 Generate Account Statement"):
            st.session_state['show_gen'] = True
            
        if st.session_state.get('show_gen'):
            card_start()
            st.subheader("Generate Statement")
            if not df.empty:
                mc = st.selectbox("Select Contractor", df['Contractor Name'].unique())
                mdr = st.date_input("Period", [])
                if st.button("Confirm & Download"):
                    if len(mdr) == 2:
                        mask = (df['Contractor Name'] == mc) & (df['Date'].dt.date >= mdr[0]) & (df['Date'].dt.date <= mdr[1])
                        f_df = df[mask]
                        if not f_df.empty:
                            path = create_pdf("statement", {"contractor": mc, "start": mdr[0], "end": mdr[1], "df": f_df})
                            with open(path, "rb") as f:
                                st.download_button("Download PDF", f, file_name=os.path.basename(path))
                        else: st.warning("No data for selection.")
                    st.session_state['show_gen'] = False
            card_end()

    # --- RAISE DEBIT NOTE ---
    elif sel == "Raise Debit Note":
        st.title("Raise Debit Note")
        card_start()
        with st.form("raise_form"):
            cons = db_get("Contractors")
            c_list = cons['Name'].tolist() if not cons.empty else []
            
            c1, c2 = st.columns(2)
            con = c1.selectbox("Contractor", c_list)
            dt = c2.date_input("Date")
            
            c3, c4 = st.columns(2)
            site = c3.text_input("Site Location")
            amt = c4.number_input("Amount (INR)", min_value=0.0)
            
            reason = st.text_area("Description / Reason")
            files = st.file_uploader("Proof (Image)", accept_multiple_files=True)
            
            if st.form_submit_button("Submit & Generate"):
                # Upload Images
                imgs, links = [], []
                if files:
                    for f in files:
                        if not os.path.exists("temp"): os.makedirs("temp")
                        p = f"temp/{f.name}"
                        with open(p, "wb") as w: w.write(f.getbuffer())
                        imgs.append(p)
                        links.append(upload_to_drive(p, f.name, f.type))
                
                # Create Data Dict
                data = {"contractor": con, "date": str(dt), "amount": amt, "reason": reason, "site": site, "local_img_paths": imgs}
                
                # Generate PDF & Upload
                pdf_path = create_pdf("receipt", data)
                pdf_link = upload_to_drive(pdf_path, os.path.basename(pdf_path), "application/pdf")
                
                # Save to DB
                db_insert("DebitNotes", [
                    int(datetime.now().timestamp()), con, str(dt), amt, reason, site, 
                    ",".join(links), pdf_link, st.session_state['username']
                ])
                
                st.success("Debit Note Raised Successfully!")
                with open(pdf_path, "rb") as f:
                    st.download_button("Download Receipt", f, file_name=os.path.basename(pdf_path))
        card_end()

    # --- ADMIN: CONTRACTORS ---
    elif sel == "Contractors" and st.session_state['role'] == "Admin":
        st.title("Contractor Management")
        c1, c2 = st.columns([1, 2])
        
        with c1:
            card_start()
            st.subheader("Manage")
            tab1, tab2, tab3 = st.tabs(["Add", "Delete", "View"])
            
            with tab1:
                with st.form("add_con"):
                    n = st.text_input("Name")
                    d = st.text_input("Details")
                    if st.form_submit_button("Add"):
                        db_insert("Contractors", [int(datetime.now().timestamp()), n, d])
                        st.success("Added"); st.rerun()
            
            with tab2:
                df_c = db_get("Contractors")
                if not df_c.empty:
                    to_del = st.selectbox("Select to Delete", df_c['Name'])
                    if st.button("Delete Contractor", type="primary"):
                        db_delete("Contractors", "Name", to_del)
                        st.warning("Deleted"); st.rerun()
            card_end()

        with c2:
            card_start()
            st.subheader("Contractor List")
            st.dataframe(db_get("Contractors"), use_container_width=True)
            card_end()

    # --- ADMIN: USERS ---
    elif sel == "User Management" and st.session_state['role'] == "Admin":
        st.title("User Management")
        c1, c2 = st.columns(2)
        
        with c1:
            card_start()
            st.subheader("Add User")
            with st.form("add_u"):
                u = st.text_input("Username")
                p = st.text_input("Password", type="password")
                r = st.selectbox("Role", ["Engineer", "Admin"])
                if st.form_submit_button("Create"):
                    db_insert("Users", [u, p, r])
                    st.success("User Created"); st.rerun()
            card_end()

        with c2:
            card_start()
            st.subheader("Manage Users")
            users = db_get("Users")
            if not users.empty:
                target = st.selectbox("Select User", users['Username'])
                act = st.radio("Action", ["Delete", "Update Role"])
                
                if act == "Delete":
                    if st.button("Delete User", type="primary"):
                        db_delete("Users", "Username", target)
                        st.warning("Deleted"); st.rerun()
                else:
                    nr = st.selectbox("New Role", ["Engineer", "Admin"])
                    if st.button("Update Role"):
                        # Column 3 is Role (index 3 in Sheets API 1-based)
                        db_update_cell("Users", target, 3, nr)
                        st.success("Updated"); st.rerun()
            card_end()
        
        card_start()
        st.dataframe(users, use_container_width=True)
        card_end()

if __name__ == "__main__":
    main()